// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package persistence

import (
	"database/sql"
	"time"
)

type Project struct {
	ID   int64
	Name string
}

type Tag struct {
	ID    int64
	Name  string
	Color sql.NullInt64
}

type Task struct {
	ID        int64
	Name      string
	ProjectID sql.NullInt64
}

type TaskTag struct {
	TagID  int64
	TaskID int64
}

type Timing struct {
	ID     int64
	Start  time.Time
	Stop   sql.NullTime
	TaskID sql.NullInt64
}
